spring:
  application:
    name: sbv

  datasource:
    url: jdbc:mariadb://localhost:3306/okestro
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect